# Generated by Django 5.2.12 on 2026-03-20 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='investment',
            name='quantity',
            field=models.DecimalField(decimal_places=12, default=1.0, max_digits=25),
        ),
    ]
