# Generated by Django 5.2.12 on 2026-03-22 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0002_alter_category_options_investment_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='Ej: 5215512345678', max_length=20, null=True, unique=True),
        ),
    ]
