# Generated by Django 5.2.12 on 2026-03-27 05:35

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0003_profile_whatsapp_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='amount_invested',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='investment',
            name='current_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
    ]
