# Generated by Django 5.2.12 on 2026-03-29 02:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0004_alter_investment_amount_invested_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NexusPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capital_extra', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('aportacion_mensual', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('preferencia_activo', models.CharField(max_length=100)),
                ('plan_json', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nexus_plans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
