# Generated by Django 5.2.12 on 2026-03-29 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0005_nexusplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='expected_yield',
            field=models.DecimalField(decimal_places=4, default=0.1, help_text='Rendimiento anual esperado en decimal (ej: 0.11 para 11%)', max_digits=5),
        ),
    ]
