# Generated by Django 5.2.12 on 2026-03-31 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0007_investment_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='telegram_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
