# Generated by Django 5.2.12 on 2026-03-31 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0008_profile_telegram_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalasset',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='investments.category'),
        ),
        migrations.AddField(
            model_name='globalasset',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='globalasset',
            name='platform',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
